"""Generate frontend/config.js from environment (or the repo-root .env).

The frontend is a no-build static site, so it can't read process env directly.
This writes a tiny `config.js` with the NON-SECRET, optional deploy settings.

IMPORTANT: the Swipe API key is deliberately NOT written here. By design it is
entered by the user in the in-app Connection panel, validated against the live
API, and stored only in their browser (localStorage). Nothing imports a Swipe
key on boot. (That's why this script no longer reads SWIPE_API_KEY.)

Env vars (all optional):
    SWIPE_API_BASE       URL of the mock backend (not a secret)
    SWIPE_SELLER_STATE   your business's state, e.g. "TELANGANA" — for a correct
                         CGST/SGST-vs-IGST split in live mode
    SWIPE_SELLER_GSTIN   your GSTIN (its first 2 digits imply the state)

The LLM agent's OpenRouter key is NO LONGER written here — it now lives on the
backend (read by the /llm proxy in mock_backend/routers/llm.py). Set
OPENROUTER_API_KEY (and optional OPENROUTER_MODEL) in the backend's environment
instead; the frontend discovers availability via the proxy's /llm/status.

SECURITY: config.js is shipped to the browser, so every value written here is
readable by anyone who loads the page. Never put the Swipe key (or any secret
you can avoid) here — proxy secrets through a backend instead.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _from_env(name: str) -> str:
    """Env var, falling back to a repo-root .env entry."""
    val = os.getenv(name, "").strip()
    if val:
        return val
    env = ROOT / ".env"
    if env.is_file():
        for line in env.read_text().splitlines():
            if line.strip().startswith(name + "="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return ""


def main() -> None:
    api_base = _from_env("SWIPE_API_BASE")
    seller_state = _from_env("SWIPE_SELLER_STATE")
    seller_gstin = _from_env("SWIPE_SELLER_GSTIN")

    lines = [
        "/* Auto-generated by scripts/gen_frontend_config.py — do not commit. */",
        "/* WARNING: anything set here ships to the browser and is publicly readable. */",
        "/* The Swipe API key is NOT set here by design — the user enters it in the */",
        "/* Connection panel; it is validated and stored only in their browser.     */",
    ]
    if api_base:
        lines.append(f"window.SWIPE_API_BASE = {json.dumps(api_base)};")
    if seller_state:
        lines.append(f"window.SWIPE_SELLER_STATE = {json.dumps(seller_state)};")
    if seller_gstin:
        lines.append(f"window.SWIPE_SELLER_GSTIN = {json.dumps(seller_gstin)};")
    (ROOT / "frontend" / "config.js").write_text("\n".join(lines) + "\n")
    print(f"Wrote frontend/config.js (no Swipe key, no LLM key — both by design; "
          f"api_base={api_base or 'default'}, seller_state={seller_state or 'unset'}). "
          f"Set OPENROUTER_API_KEY in the BACKEND env to enable the LLM agent.")


if __name__ == "__main__":
    main()
