"""Generate frontend/config.js from environment (or the repo-root .env).

The frontend is a no-build static site, so it can't read process env directly.
This writes a tiny `config.js` that sets `window.SWIPE_API_TOKEN` / `SWIPE_MODE`
from env vars — run it at deploy time (e.g. as your host's build command) so the
hosted app always boots with your key:

    SWIPE_API_KEY=...  python scripts/gen_frontend_config.py
    # or, locally, it falls back to reading .env

Env vars:
    SWIPE_API_KEY        (required) your Swipe Partner API key
    SWIPE_MODE           (optional) "live" (default) or "mock"
    SWIPE_SELLER_STATE   (optional) your business's state, e.g. "TELANGANA" —
                         needed for a correct CGST/SGST-vs-IGST split in live mode
    SWIPE_SELLER_GSTIN   (optional) your GSTIN (its first 2 digits imply the state)
    OPENROUTER_API_KEY   (optional) enables the LLM agent brain
    OPENROUTER_MODEL     (optional) default "openai/gpt-4o-mini"

SECURITY: config.js is shipped to the browser, so every value here (including
the API keys) is readable by anyone who loads the page. That's acceptable for a
single-account demo, but for anything public, proxy the keys through a backend
instead of embedding them.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _from_env(name: str) -> str:
    """Env var, falling back to a repo-root .env entry."""
    val = os.getenv(name, "").strip()
    if val:
        return val
    env = ROOT / ".env"
    if env.is_file():
        for line in env.read_text().splitlines():
            if line.strip().startswith(name + "="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return ""


def main() -> None:
    key = _from_env("SWIPE_API_KEY")
    if not key:
        raise SystemExit("SWIPE_API_KEY not set (env or .env).")
    mode = os.getenv("SWIPE_MODE", "live").strip() or "live"
    seller_state = _from_env("SWIPE_SELLER_STATE")
    seller_gstin = _from_env("SWIPE_SELLER_GSTIN")
    llm_key = _from_env("OPENROUTER_API_KEY")
    llm_model = os.getenv("OPENROUTER_MODEL", "").strip() or "openai/gpt-4o-mini"

    # json.dumps safely escapes the values into valid JS string literals.
    lines = [
        "/* Auto-generated by scripts/gen_frontend_config.py — do not commit. */",
        "/* WARNING: these values ship to the browser and are publicly readable. */",
        f"window.SWIPE_API_TOKEN = {json.dumps(key)};",
        f"window.SWIPE_MODE = {json.dumps(mode)};",
    ]
    if seller_state:
        lines.append(f"window.SWIPE_SELLER_STATE = {json.dumps(seller_state)};")
    if seller_gstin:
        lines.append(f"window.SWIPE_SELLER_GSTIN = {json.dumps(seller_gstin)};")
    if llm_key:
        lines.append(f"window.OPENROUTER_API_KEY = {json.dumps(llm_key)};")
        lines.append(f"window.OPENROUTER_MODEL = {json.dumps(llm_model)};")
    (ROOT / "frontend" / "config.js").write_text("\n".join(lines) + "\n")
    print(f"Wrote frontend/config.js (mode={mode}, swipe=…{key[-6:]}, "
          f"seller_state={seller_state or 'unset'}, "
          f"llm={'on/' + llm_model if llm_key else 'off'}).")


if __name__ == "__main__":
    main()
